Train:
  batch_size: 128
  learning_rate: 0.001
  reg: 0.0005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: ResNet-32 # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: imbalance # regular or imbalance
  reweight: True
  beta: 0.99999
  save_best: True

loss:
  loss_type: Focal # CE or Focal